// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetEmployee(ctx context.Context, id int64) (Employee, error)
	GetLocation(ctx context.Context, id int64) (Location, error)
	GetMembership(ctx context.Context, userid int64) (Membership, error)
	GetUser(ctx context.Context, name string) (User, error)
}

var _ Querier = (*Queries)(nil)
